name: issues to discussions

on:
  issues:
    types: [closed]

jobs:
  check-labels:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Reopen issue when label count is not exactly one
        uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue;
            const labels = issue.labels || [];

            if (labels.length !== 1) {
              console.log("label을 반드시 하나만 선택해야 합니다.");

              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                state: "open"
              });
              throw new Error("라벨 없음 - 이슈 재오픈 후 워크플로우 종료");
            }
            console.log("label이 유일하여 다음 작업을 진행합니다.");

  create-discussions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.3.0
        with:
          node-version: '20'

      - name: Get Label Id from issue
        uses: actions/github-script@v7
        with:
          script: return context.payload.issue.labels[0].node_id;
          result-encoding: string

      - name: Run create-discussions script
        working-directory: ./scripts
        run: |
          npm install
          node create-discussions.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY_ID: ${{ secrets.REPOSITORY_ID }}
          CATEGORY_ID: ${{ secrets.CATEGORY_ID }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          LABEL_ID: ${{ steps.get-label-id.outputs.result }}
