name: issues to discussions

on:
  issues:
    types: [closed]

jobs:
  check-labels:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install action dependencies
        run: npm install @actions/core @actions/github

      - name: Reopen issue if no labels are assigned
        run: node .github/scripts/utils/labelsValidator.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  create-discussions:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.3.0
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Get Label Id from issue
        id: get-label-id
        uses: actions/github-script@v7
        with:
          script: return context.payload.issue.labels.map(label => label.node_id).join(',');
          result-encoding: string

      - name: Create Discussions
        working-directory: .github/scripts
        run: node index.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY_ID: ${{ secrets.REPOSITORY_ID }}
          CATEGORY_ID: ${{ secrets.CATEGORY_ID }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          LABEL_IDS: ${{ steps.get-label-id.outputs.result }}
